import SwiftUI
import AppKit


struct ReviewMediaStrip: View {
    let day: DayName
    let postingDay: PostingDay
    var previewPaths: [String: String]? = nil
    var isRegenerating: Bool = false
    var graphicVersion: Int = 0
    var onPreview: ((URL) -> Void)?
    var onRegenerate: (() -> Void)? = nil
    /// When non-nil, the before/after pair shows an "Add / Change B&W" control
    /// (Tuesday only). Picking re-runs the 3-photo treatment for Tuesday + Friday.
    var onChangeBW: (() -> Void)? = nil
    var onRemoveBW: (() -> Void)? = nil
    /// Replace the whole Wednesday collage photo set (review-screen action).
    var onChangeCollagePhotos: (() -> Void)? = nil
    var collageCropOffsets: Binding<[String: CropOffset]>? = nil
    var collageCellOverride: Binding<[CollageCell]?>? = nil
    /// When true, skip the main story/reel/before-after graphic — used by the split
    /// layout's right column so the preview doesn't appear twice.
    var hideMainGraphic: Bool = false

    /// Which of this day's cached assets predate the current design (#160, #286).
    ///
    /// #160 asked this of the collage alone. The reels and stills went through
    /// the same gallery redesign with no stamp, so a cached scroll reel or
    /// before/after from before it kept rendering the old look indefinitely, and
    /// the reels are the worst case: re-rendering one is expensive enough that
    /// nobody does it speculatively.
    ///
    /// Held in state and read on appear rather than checked in `body`, because
    /// it lists a directory and `body` runs on every redraw. The export screen
    /// took this shape for the same reason (#247); the first version of this row
    /// did not, which is a disk read per redraw for an answer that changes only
    /// when the day is regenerated.
    @State private var staleTemplates: [String] = []

    /// Reel video path for this day (Tuesday / Thursday only).
    private var reelURL: URL? {
        guard let p = previewPaths?["reel"],
              FileManager.default.fileExists(atPath: p) else { return nil }
        return URL(fileURLWithPath: p)
    }

    /// Collage PNG + layout sidecar — any collage day (the "collage" key is only
    /// present for collage-carousel days: Wednesday always, Sun/Mon under balanced).
    private var collageInfo: (url: URL, layoutURL: URL)? {
        guard let p = previewPaths?["collage"],
              FileManager.default.fileExists(atPath: p) else { return nil }
        let url = URL(fileURLWithPath: p)
        return (url, LayoutSidecar.url(for: url))
    }

    /// Best still preview graphic path for non-collage days, in priority order.
    private var previewGraphicURL: (url: URL, label: String)? {
        guard let paths = previewPaths else { return nil }
        let priority: [(String, String)] = [
            ("before_after", "BEFORE / AFTER"),
            ("story_cover",  "STORY COVER"),
            ("story",        "STORY"),
        ]
        for (key, label) in priority {
            if let p = paths[key], FileManager.default.fileExists(atPath: p) {
                return (URL(fileURLWithPath: p), label)
            }
        }
        return nil
    }

    /// The folder this day's cached assets live in.
    ///
    /// Taken from a preview path the run itself produced rather than rebuilt
    /// from the event and day, because the folder name is Python's to choose and
    /// a second derivation of it would break silently the first time it changed.
    private var dayFolder: URL? {
        guard let path = previewPaths?.values.first(where: {
            FileManager.default.fileExists(atPath: $0)
        }) else { return nil }
        return URL(fileURLWithPath: path).deletingLastPathComponent()
    }

    /// Re-read the day's design stamp. Cheap, and only on the two events that
    /// can change the answer: arriving at the day, and finishing a regeneration
    /// of it.
    private func refreshDesignStaleness() {
        staleTemplates = dayFolder.map { DesignStamp.staleTemplates(in: $0) } ?? []
    }

    var body: some View {
        VStack(alignment: .leading, spacing: Spacing.sm) {
            // Assets cached before the current design were rendered by the old
            // look, and will keep rendering it until this day is regenerated by
            // hand. Nothing surfaced that, so a redesign left old assets in
            // place indefinitely (#160 for the collage, #286 for the rest).
            //
            // Above the previews rather than beside one of them, because it can
            // now name several assets at once and the reels are the ones worth
            // saying it about: re-rendering a reel is expensive enough that
            // nobody does it speculatively, so a stale one survives longest.
            if let message = DesignStamp.staleMessage(for: staleTemplates), let onRegenerate {
                BrandBanner(
                    icon: "clock.arrow.circlepath",
                    message: message,
                    style: .warning,
                    actions: [BrandBannerAction(label: "Regenerate day",
                                                action: onRegenerate)]
                )
                .padding(.horizontal, Spacing.xl)
            }

            // Reel video (Tuesday speed edit / Thursday scroll)
            if !hideMainGraphic, let url = reelURL {
                VStack(alignment: .leading, spacing: 4) {
                    Text("REEL")
                        .font(.system(size: 9, weight: .medium))
                        .tracking(0.8)
                        .foregroundStyle(PaintedSurfaces.secondaryText)
                        .padding(.horizontal, Spacing.xl)
                    ReelPreviewPlayer(url: url, version: graphicVersion, onRegenerate: onRegenerate, isRegenerating: isRegenerating)
                        .id("\(url.path)-\(graphicVersion)")
                        .aspectRatio(9/16, contentMode: .fit)
                        .frame(maxWidth: .infinity, maxHeight: max(440, (NSScreen.main?.visibleFrame.height ?? 800) * 0.82))
                        .padding(.horizontal, Spacing.xl)
                }
            } else if !hideMainGraphic, reelURL == nil, (day == .tuesday || day == .thursday) {
                // No reel generated yet — offer a button to generate it
                VStack(spacing: Spacing.sm) {
                    Text("No reel generated yet")
                        .font(.light(12))
                        .foregroundStyle(PaintedSurfaces.secondaryText)
                    if isRegenerating {
                        ProgressView()
                            .controlSize(.small)
                            .tint(PaintedSurfaces.iconAccent)
                    } else if let onRegenerate {
                        Button("Generate Reel") { onRegenerate() }
                            .buttonStyle(BrandButtonStyle())
                    }
                }
                .frame(maxWidth: .infinity)
                .padding(.vertical, Spacing.lg)
                .padding(.horizontal, Spacing.xl)
            }

            // Wednesday: interactive collage with per-cell crop controls
            if let (url, layoutURL) = collageInfo {
                VStack(alignment: .leading, spacing: 4) {
                    HStack {
                        Text("COLLAGE")
                            .font(.system(size: 9, weight: .medium))
                            .tracking(0.8)
                            .foregroundStyle(PaintedSurfaces.secondaryText)
                        Spacer()
                        Text("Drag photo to reposition · tap to select · drag borders to resize")
                            .font(.system(size: 9))
                            .foregroundStyle(PaintedSurfaces.secondaryText)
                    }
                    .padding(.horizontal, Spacing.xl)


                    if let offsets = collageCropOffsets {
                        CollagePreviewThumbnail(
                            url: url,
                            layoutURL: layoutURL,
                            cropOffsets: offsets,
                            cellOverride: collageCellOverride ?? .constant(nil),
                            onPreview: { onPreview?(url) },
                            isRegenerating: isRegenerating,
                            onRegenerate: onRegenerate,
                            onChangePhotos: onChangeCollagePhotos
                        )
                        // No .id() here — image reload is handled internally via
                        // .task(id: url) and .onChange(of: isRegenerating), so the
                        // view is never destroyed and selectedCellIndex (+ slider) persists.
                        .padding(.horizontal, Spacing.xl)
                    } else {
                        PreviewGraphicThumbnail(
                            url: url,
                            onPreview: { onPreview?(url) },
                            isRegenerating: isRegenerating,
                            onRegenerate: onRegenerate
                        )
                        .id("\(url.path)-\(graphicVersion)")
                        .padding(.horizontal, Spacing.xl)
                    }
                }
            }

            // Other days: still preview graphic (before/after, story cover, story)
            if !hideMainGraphic, let (url, label) = previewGraphicURL {
                VStack(alignment: .leading, spacing: 4) {
                    Text(label)
                        .font(.system(size: 9, weight: .medium))
                        .tracking(0.8)
                        .foregroundStyle(PaintedSurfaces.secondaryText)
                        .padding(.horizontal, Spacing.xl)

                    PreviewGraphicThumbnail(
                            url: url,
                            onPreview: { onPreview?(url) },
                            isRegenerating: isRegenerating,
                            onRegenerate: onRegenerate
                        )
                        .id("\(url.path)-\(graphicVersion)")
                        .padding(.horizontal, Spacing.xl)
                }
            }

            // Uploaded source photos (all days — plain thumbnails for preview/tap only)
            if !postingDay.photoPaths.isEmpty {
                FadingScrollView(axis: .horizontal) {
                    HStack(spacing: 8) {
                        ForEach(postingDay.photoPaths, id: \.self) { url in
                            ReviewThumb(url: url) { onPreview?(url) }
                                .onDrag { NSItemProvider(object: url.path as NSString) }
                        }
                    }
                    .padding(.horizontal, Spacing.xl)
                    .padding(.vertical, 2)
                }
            }

            // Before / After pair — Tuesday and Friday. A third B&W after shows
            // when the 3-photo treatment is in use.
            if day == .tuesday || day == .friday {
                let hasBA = postingDay.rawPhotoPath != nil
                    || postingDay.editedPhotoPath != nil
                    || postingDay.bwPhotoPath != nil
                if hasBA {
                    HStack(alignment: .top, spacing: 12) {
                        if let raw = postingDay.rawPhotoPath {
                            LabeledReviewThumb(url: raw, label: "Before") { onPreview?(raw) }
                        }
                        if let edited = postingDay.editedPhotoPath {
                            LabeledReviewThumb(url: edited, label: postingDay.bwPhotoPath != nil ? "Color" : "After") { onPreview?(edited) }
                        }
                        if let bw = postingDay.bwPhotoPath {
                            LabeledReviewThumb(url: bw, label: "B&W") { onPreview?(bw) }
                        }

                        // Add / Change B&W control (Tuesday only — Friday mirrors it).
                        if let onChangeBW {
                            if postingDay.bwPhotoPath == nil {
                                Button { onChangeBW() } label: {
                                    VStack(spacing: 4) {
                                        Image(systemName: "plus.circle")
                                            .font(.system(size: 18))
                                        Text("Add B&W")
                                            .font(.system(size: 9))
                                    }
                                    .foregroundStyle(PaintedSurfaces.pageAccentText)
                                    .frame(width: 60, height: 80)
                                    .background(PaintedSurfaces.addTreatmentFill)
                                    .clipShape(RoundedRectangle(cornerRadius: Radius.sm))
                                }
                                .buttonStyle(.plain)
                                .disabled(isRegenerating)
                            } else {
                                VStack(spacing: 6) {
                                    Button("Change") { onChangeBW() }
                                        .buttonStyle(.plain)
                                        .font(.system(size: 10))
                                        .foregroundStyle(PaintedSurfaces.pageAccentText)
                                    Button("Remove") { onRemoveBW?() }
                                        .buttonStyle(.plain)
                                        .font(.system(size: 10))
                                        .foregroundStyle(PaintedSurfaces.secondaryText)
                                }
                                .disabled(isRegenerating)
                                .padding(.top, 4)
                            }
                        }
                    }
                    .padding(.horizontal, Spacing.xl)
                }
            }

            // Tuesday: screen recording
            if day == .tuesday, let rec = postingDay.screenRecordingPath {
                ReviewMediaFileRow(url: rec, icon: "film", label: "Screen recording")
                    .padding(.horizontal, Spacing.xl)
            }

            // Thursday / Tuesday: audio
            if let audio = postingDay.audioPath {
                ReviewMediaFileRow(url: audio, icon: "waveform", label: "Audio")
                    .padding(.horizontal, Spacing.xl)
            } else if let fetched = postingDay.reelAudioSource {
                // The track a swap fetched, which is not `audioPath` (that only
                // ever holds a file Dan uploaded). Before #262 this was written
                // by Python, read by nobody, and the music in the reel had no
                // name anywhere on screen.
                ReviewMediaFileRow(
                    url: fetched, icon: "waveform",
                    label: postingDay.reelAudioTags.isEmpty
                        ? "Audio"
                        : "Audio (matched on \(postingDay.reelAudioTags))"
                )
                .padding(.horizontal, Spacing.xl)
            }
        }
        .padding(.bottom, Spacing.xs)
        .onAppear { refreshDesignStaleness() }
        // A finished regeneration rewrites the stamp with the current design,
        // so the badge has to go without leaving the screen. graphicVersion is
        // bumped by every completed render of this day.
        .onChange(of: graphicVersion) { _, _ in refreshDesignStaleness() }
        .onChange(of: isRegenerating) { _, running in
            if !running { refreshDesignStaleness() }
        }
    }
}

// MARK: - Friday pipeline status (elapsed time / stall, not a bare spinner)

/// Live elapsed-time status for Friday's clip pipeline (import copy, Stage 1
/// scoring, Stage 2 Claude selection, ffmpeg render). Distinguishes started
/// / still-alive-with-elapsed-time / taking-longer-than-usual so the user
/// never sees a spinner that looks identical whether it's progressing,
/// hung, or dead.
struct PipelineStatusView: View {
    let startedAt: Date?

    var body: some View {
        TimelineView(.periodic(from: .now, by: 1)) { context in
            let state = PipelineProgressState.state(startedAt: startedAt, now: context.date, failedMessage: nil)
            switch state {
            case .idle, .failed:
                EmptyView()
            case .running(let seconds):
                HStack(spacing: Spacing.xs) {
                    ProgressView().controlSize(.small).tint(PaintedSurfaces.iconAccent)
                    Text("Working… \(seconds)s")
                        .font(.system(size: 11))
                        .foregroundStyle(PaintedSurfaces.secondaryText)
                }
            case .stalled(let seconds):
                HStack(spacing: Spacing.xs) {
                    Image(systemName: "exclamationmark.triangle")
                        .foregroundStyle(PaintedSurfaces.pageAccentText)
                    Text("Still working (\(seconds)s): this is taking longer than usual")
                        .font(.system(size: 11))
                        .foregroundStyle(PaintedSurfaces.pageAccentText)
                }
            }
        }
    }
}
